default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: task_project_development

test:
  <<: *default
  database: task_project_test